name: Open Github Issue
author: Kenji Emura
descritpion: Opens a github issue

inputs:
  token:
    description: "The auth token to access Github"
    required: true
  title:
    description: "Issue title"
    required: true
  body:
    description: "Issue body"
  assignees:
    description: "Issue assignees"

outputs:
  issue:
    description: "The issue object as a json string"

runs:
  using: "node12"
  # This is the file that will be run
  main: "dist/index.js"
