name: Custom Actions
on:
  repository_dispatch:
    types: [custom_action]

jobs:
  test-action-javascript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/test_action
        id: hello
        with:
          who-to-greet: "Kenji Emura"
      - name: Run the greeting time
        run: |
          echo "Time: ${{ steps.hello.outputs.time }}"
          echo "The custom env variable that we created says: $CUSTOM_ENV_VARIABLE"

  test-action-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/docker_test_action
        id: hello
        with:
          who-to-greet: "Kenji Emura"
      - name: Run the greeting time
        run: |
          echo "Time: ${{ steps.hello.outputs.time }}"
          echo "The custom env variable that we created says: $CUSTOM_ENV_VARIABLE"

  create-issue-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/generate_issue
        id: create_issue
        with:
          token: ${{ secrets.ADMIN_TOKEN }}
          title: Automatic issue created from the 'custom_action.yaml'
          body: The 'custom_action.yaml' has two jobs, this issue is created from the second one.
          assignees: |
            kenjiemura
      - run: |
          echo "steps.create_issue: ${{ steps.create_issue }}"
