name: Custom Action
on:
  repository_dispatch:
    types: [custom_action]

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/hello
        id: hello
        with:
          who-to-greet: "Kenji Emura"
      - name: Run the greeting time
        run: |
          echo "Time: ${{ steps.hello.outputs.time }}"
